### ISSUE TITLE
Renovations not working in SDV 1.5

### ISSUE THREAD

**Issue by The4thLaw** [LeonBlade/TreeTransplant#17]
Hello,

Using the TreeTransplant mod makes it impossible to access the new house renovations introduced in SDV 1.5 and described here : https://stardewvalleywiki.com/Carpenter%27s_Shop#House_Renovations

**Expected behaviour**
When talking to Robin with TreeTransplant installed, it is possible to move trees **and** to access the menu for house renovations.

**Actual behaviour**
When talking to Robin with TreeTransplant installed, it is possible to move trees but the menu for house renovations doesn't appear.

**Comment by The4thLaw** [comment]
I had a quick look at the source code and the issue is most likely in [handleDialogueMenu](https://github.com/LeonBlade/TreeTransplant/blob/d420d0aad9860b8640d65732cec519a9c841eb2c/TreeTransplant/TreeTransplant.cs#L66), since you redefine the whole menu.

I don't have a development environment to try to submit a PR, though, sorry.

**Comment by LeonBlade** [comment]
Thanks, I forgot about this. I’ll try to fix it soon.

**Comment by LeonBlade** [comment]
This should be working now. If for some reason it's not, please let me know and reopen this issue.

**Comment by The4thLaw** [comment]
The menu appears but clicking on it doesn't trigger the renovations menu. I'm running SDV 1.5.1 in French with SMAPI 3.8.1. I don't see anything specific in the logs. Let me know if you want me to try anything else.

**Comment by The4thLaw** [comment]
v1.0.13 works, thanks :)

**Comment by LeonBlade** [comment]
Thank you for the report!
