### ISSUE TITLE
Incompatible with FarmExpansion

### ISSUE THREAD

**Issue by InsaneJ** [LeonBlade/TreeTransplant#3]
Using TreeTransplant 1.0.1, FarmExpansion 3.0.2 and SMAPI 1.15.4.
I don't get the option to "Transplant Trees" when talking to Robin. My SMAPI log shows no errors.
SMAPI log: https://paste2.org/Os9wgj1H

FarmExpansion: https://www.nexusmods.com/stardewvalley/mods/130/?
This mod adds a menu option to Robin's farm building menu. I'm assuming this is part of the reason why these mods don't work together well. Is there anything you can do to make these mods compatible?

I've also posted this issue on FarmExpansion's Github, here: https://github.com/AdvizeGH/FarmExpansion/issues/2

**Comment by AdvizeGH** [comment]
Farm Expansion replaces the action property in the "ScienceHouse" location:

`Game1.getLocationFromName("ScienceHouse").setTileProperty(8, 19, "Buildings", "Action", "FECarpenter");`

This tile property, when clicked upon, executes a block of code which includes:

`Game1.currentLocation.createQuestionDialogue(Game1.content.LoadString("Strings\\Locations:ScienceHouse_CarpenterMenu"), answerChoices, carpenter2, null);`

This prevents Game1.currentLocation.lastQuestionKey from ever being equal to "carpenter"... which Tree Transplant depends on when injecting its custom menu option.

I'm open to making necessary changes to Farm Expansion to allow these mods to remain compatible. I don't believe it'll be particularly challenging.

**Comment by LeonBlade** [comment]
@AdvizeGH How do you propose we solve this issue?  I'm fine for replacing the tile over injecting in the existing question dialogue.  Let me know which you prefer and we can adjust the code accordingly.

**Comment by AdvizeGH** [comment]
@LeonBlade I have a few ideas but not sure yet which is best. I'll poke around some more after I get home from work and propose a solution.

**Comment by Corverne** [comment]
@AdvizeGH @LeonBlade I've been having this issue too, and I wound up on this thread in my search, so that answers a lot of questions for me, phew. I wasn't looking forward to trying to tackle my massive mod list to find the conflict! I'm glad you guys are working on it, thank you!

**Comment by AdvizeGH** [comment]
Fixed as of Farm Expansion 3.1 which is now available for download. No changes required to TreeTransplant.

**Comment by Corverne** [comment]
I just tested it as soon as I saw the Farm Expansion update and it works! Thank you, @AdvizeGH !

**Comment by LeonBlade** [comment]
Since this has been tested as well I can now close the issue!
